from enum import Enum


class MerchantEventType(str, Enum):
    MERCHANT_CREATED = "MERCHANT_CREATED"
    APP_INSTALLED = "APP_INSTALLED"
    APP_UNINSTALLED = "APP_UNINSTALLED"
    SUBSCRIPTION_STARTED = "SUBSCRIPTION_STARTED"
    SUBSCRIPTION_RENEWED = "SUBSCRIPTION_RENEWED"
    SUBSCRIPTION_UPGRADED = "SUBSCRIPTION_UPGRADED"
    SUBSCRIPTION_DOWNGRADED = "SUBSCRIPTION_DOWNGRADED"
    SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED"
    FEATURE_ENABLED = "FEATURE_ENABLED"
    FEATURE_DISABLED = "FEATURE_DISABLED"
    MERCHANT_CONFIGURATION_UPDATED = "MERCHANT_CONFIGURATION_UPDATED"
    MERCHANT_LOGIN = "MERCHANT_LOGIN"


class ProductEventType(str, Enum):
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_ARCHIVED = "PRODUCT_ARCHIVED"
    PRODUCT_VARIANT_CREATED = "PRODUCT_VARIANT_CREATED"
    PRODUCT_VARIANT_UPDATED = "PRODUCT_VARIANT_UPDATED"
    PRODUCT_VARIANT_ARCHIVED = "PRODUCT_VARIANT_ARCHIVED"


class ShopperEventType(str, Enum):
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_ENDED = "SESSION_ENDED"
    PRODUCT_VIEWED = "PRODUCT_VIEWED"
    PRODUCT_SEARCHED = "PRODUCT_SEARCHED"
    WISHLIST_ADDED = "WISHLIST_ADDED"
    WISHLIST_REMOVED = "WISHLIST_REMOVED"
    SAVE_FOR_LATER_ADDED = "SAVE_FOR_LATER_ADDED"
    SAVE_FOR_LATER_REMOVED = "SAVE_FOR_LATER_REMOVED"
    ADD_TO_CART = "ADD_TO_CART"
    REMOVE_FROM_CART = "REMOVE_FROM_CART"
    CHECKOUT_STARTED = "CHECKOUT_STARTED"
    PURCHASE_COMPLETED = "PURCHASE_COMPLETED"
    RECOMMENDATION_VIEWED = "RECOMMENDATION_VIEWED"
    RECOMMENDATION_CLICKED = "RECOMMENDATION_CLICKED"


class CampaignEventType(str, Enum):
    EMAIL_DELIVERED = "EMAIL_DELIVERED"
    EMAIL_OPENED = "EMAIL_OPENED"
    EMAIL_CLICKED = "EMAIL_CLICKED"
    SMS_DELIVERED = "SMS_DELIVERED"
    SMS_CLICKED = "SMS_CLICKED"
    PUSH_DELIVERED = "PUSH_DELIVERED"
    PUSH_OPENED = "PUSH_OPENED"
    AD_VIEWED = "AD_VIEWED"
    AD_CLICKED = "AD_CLICKED"
    CAMPAIGN_CONVERTED = "CAMPAIGN_CONVERTED"


class PlatformEventType(str, Enum):
    MERCHANT_PROFILE_GENERATED = "MERCHANT_PROFILE_GENERATED"
    SHOPPER_PROFILE_GENERATED = "SHOPPER_PROFILE_GENERATED"
    SEGMENT_MEMBERSHIP_REFRESHED = "SEGMENT_MEMBERSHIP_REFRESHED"
    BUSINESS_METRICS_GENERATED = "BUSINESS_METRICS_GENERATED"
    AI_KNOWLEDGE_GENERATED = "AI_KNOWLEDGE_GENERATED"
    RECOMMENDATION_GENERATED = "RECOMMENDATION_GENERATED"
    SCHEDULED_JOB_COMPLETED = "SCHEDULED_JOB_COMPLETED"
