"""Add FeatureEventMapping

Revision ID: 3a8ae5045daa
Revises: 92ca5c8ed9ed
Create Date: 2026-09-23 21:47:34.630509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8ae5045daa'
down_revision: Union[str, Sequence[str], None] = '92ca5c8ed9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_event_mappings',
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('event_domain', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['platform_features.feature_id'], ),
    sa.PrimaryKeyConstraint('event_domain', 'event_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_event_mappings')
    # ### end Alembic commands ###
