"""shopper schema adjustments and event contracts

Revision ID: 48ca431b15ea
Revises: df49fbe0e3b9
Create Date: 2026-09-19 18:54:16.446295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ca431b15ea'
down_revision: Union[str, Sequence[str], None] = 'df49fbe0e3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopper_events', sa.Column('session_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_shopper_events_session_id'), 'shopper_events', ['session_id'], unique=False)
    op.alter_column('shoppers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shoppers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_shopper_events_session_id'), table_name='shopper_events')
    op.drop_column('shopper_events', 'session_id')
    # ### end Alembic commands ###
