"""event tables

Revision ID: 5cbf5df7b3d7
Revises: d56a4ead422e
Create Date: 2026-09-12 20:27:04.326967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cbf5df7b3d7'
down_revision: Union[str, Sequence[str], None] = 'd56a4ead422e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_platform_events_event_timestamp'), 'platform_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_platform_events_event_type'), 'platform_events', ['event_type'], unique=False)
    op.create_table('merchant_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_merchant_events_event_type'), 'merchant_events', ['event_type'], unique=False)
    op.create_index('ix_merchant_events_merchant_id_event_timestamp', 'merchant_events', ['merchant_id', 'event_timestamp'], unique=False)
    op.create_index(op.f('ix_merchant_events_processed'), 'merchant_events', ['processed'], unique=False)
    op.create_table('shopper_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('shopper_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['shopper_id'], ['shoppers.shopper_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_shopper_events_event_type'), 'shopper_events', ['event_type'], unique=False)
    op.create_index('ix_shopper_events_merchant_id_event_timestamp', 'shopper_events', ['merchant_id', 'event_timestamp'], unique=False)
    op.create_index(op.f('ix_shopper_events_processed'), 'shopper_events', ['processed'], unique=False)
    op.create_index('ix_shopper_events_shopper_id_event_timestamp', 'shopper_events', ['shopper_id', 'event_timestamp'], unique=False)
    op.create_table('campaign_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('shopper_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['shopper_id'], ['shoppers.shopper_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_campaign_events_campaign_id_event_timestamp', 'campaign_events', ['campaign_id', 'event_timestamp'], unique=False)
    op.create_index(op.f('ix_campaign_events_event_type'), 'campaign_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_campaign_events_processed'), 'campaign_events', ['processed'], unique=False)
    op.create_index('ix_campaign_events_shopper_id_event_timestamp', 'campaign_events', ['shopper_id', 'event_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_campaign_events_shopper_id_event_timestamp', table_name='campaign_events')
    op.drop_index(op.f('ix_campaign_events_processed'), table_name='campaign_events')
    op.drop_index(op.f('ix_campaign_events_event_type'), table_name='campaign_events')
    op.drop_index('ix_campaign_events_campaign_id_event_timestamp', table_name='campaign_events')
    op.drop_table('campaign_events')
    op.drop_index('ix_shopper_events_shopper_id_event_timestamp', table_name='shopper_events')
    op.drop_index(op.f('ix_shopper_events_processed'), table_name='shopper_events')
    op.drop_index('ix_shopper_events_merchant_id_event_timestamp', table_name='shopper_events')
    op.drop_index(op.f('ix_shopper_events_event_type'), table_name='shopper_events')
    op.drop_table('shopper_events')
    op.drop_index(op.f('ix_merchant_events_processed'), table_name='merchant_events')
    op.drop_index('ix_merchant_events_merchant_id_event_timestamp', table_name='merchant_events')
    op.drop_index(op.f('ix_merchant_events_event_type'), table_name='merchant_events')
    op.drop_table('merchant_events')
    op.drop_index(op.f('ix_platform_events_event_type'), table_name='platform_events')
    op.drop_index(op.f('ix_platform_events_event_timestamp'), table_name='platform_events')
    op.drop_table('platform_events')
    # ### end Alembic commands ###
