"""daily analytics and metrics

Revision ID: 9131d3af4ed2
Revises: 976ebe15a49d
Create Date: 2026-09-12 22:41:06.087433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9131d3af4ed2'
down_revision: Union[str, Sequence[str], None] = '976ebe15a49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_metrics_daily',
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('active_merchants', sa.Integer(), nullable=False),
    sa.Column('new_merchants', sa.Integer(), nullable=False),
    sa.Column('installed_merchants', sa.Integer(), nullable=False),
    sa.Column('uninstalled_merchants', sa.Integer(), nullable=False),
    sa.Column('new_subscriptions', sa.Integer(), nullable=False),
    sa.Column('subscription_upgrades', sa.Integer(), nullable=False),
    sa.Column('subscription_downgrades', sa.Integer(), nullable=False),
    sa.Column('subscription_cancellations', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('active_shoppers', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('metric_date')
    )
    op.create_table('feature_metrics_daily',
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('eligible_merchant_count', sa.Integer(), nullable=False),
    sa.Column('enabled_merchant_count', sa.Integer(), nullable=False),
    sa.Column('active_merchant_count', sa.Integer(), nullable=False),
    sa.Column('feature_event_count', sa.Integer(), nullable=False),
    sa.Column('adoption_rate', sa.Numeric(), nullable=False),
    sa.Column('usage_rate', sa.Numeric(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['platform_features.feature_id'], ),
    sa.PrimaryKeyConstraint('feature_id', 'metric_date')
    )
    op.create_table('merchant_metrics_daily',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('unique_shoppers', sa.Integer(), nullable=False),
    sa.Column('new_shoppers', sa.Integer(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('converted_session_count', sa.Integer(), nullable=False),
    sa.Column('product_view_count', sa.Integer(), nullable=False),
    sa.Column('wishlist_add_count', sa.Integer(), nullable=False),
    sa.Column('save_for_later_count', sa.Integer(), nullable=False),
    sa.Column('add_to_cart_count', sa.Integer(), nullable=False),
    sa.Column('checkout_count', sa.Integer(), nullable=False),
    sa.Column('purchase_count', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(), nullable=False),
    sa.Column('average_order_value', sa.Numeric(), nullable=False),
    sa.Column('platform_login_count', sa.Integer(), nullable=False),
    sa.Column('campaign_created_count', sa.Integer(), nullable=False),
    sa.Column('feature_enable_count', sa.Integer(), nullable=False),
    sa.Column('feature_disable_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('merchant_id', 'metric_date')
    )
    op.create_table('campaign_analytics_daily',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('opened_count', sa.Integer(), nullable=False),
    sa.Column('clicked_count', sa.Integer(), nullable=False),
    sa.Column('converted_count', sa.Integer(), nullable=False),
    sa.Column('attributed_order_count', sa.Integer(), nullable=False),
    sa.Column('attributed_revenue', sa.Numeric(), nullable=False),
    sa.Column('open_rate', sa.Numeric(), nullable=False),
    sa.Column('click_through_rate', sa.Numeric(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'metric_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_analytics_daily')
    op.drop_table('merchant_metrics_daily')
    op.drop_table('feature_metrics_daily')
    op.drop_table('platform_metrics_daily')
    # ### end Alembic commands ###
