"""make campaign_events shopper_id nullable

Revision ID: 92ca5c8ed9ed
Revises: 48ca431b15ea
Create Date: 2026-09-20 11:50:06.311592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ca5c8ed9ed'
down_revision: Union[str, Sequence[str], None] = '48ca431b15ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_events', 'shopper_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_events', 'shopper_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
