"""derived profiles journeys segmentation merchant health

Revision ID: 976ebe15a49d
Revises: 5cbf5df7b3d7
Create Date: 2026-09-12 22:09:46.763302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976ebe15a49d'
down_revision: Union[str, Sequence[str], None] = '5cbf5df7b3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_health',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('health_score', sa.Numeric(), nullable=False),
    sa.Column('health_status', sa.String(), nullable=False),
    sa.Column('churn_risk_score', sa.Numeric(), nullable=False),
    sa.Column('engagement_score', sa.Numeric(), nullable=False),
    sa.Column('feature_adoption_score', sa.Numeric(), nullable=False),
    sa.Column('business_performance_score', sa.Numeric(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('merchant_journeys',
    sa.Column('merchant_journey_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('journey_status', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('merchant_journey_id')
    )
    op.create_table('merchant_profiles',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('total_shoppers', sa.Integer(), nullable=False),
    sa.Column('total_products', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(), nullable=False),
    sa.Column('average_order_value', sa.Numeric(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(), nullable=False),
    sa.Column('total_campaigns', sa.Integer(), nullable=False),
    sa.Column('active_campaign_count', sa.Integer(), nullable=False),
    sa.Column('enabled_feature_count', sa.Integer(), nullable=False),
    sa.Column('last_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_campaign_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('merchant_journey_events',
    sa.Column('merchant_journey_event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_journey_id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_journey_id'], ['merchant_journeys.merchant_journey_id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['merchant_events.event_id'], ),
    sa.PrimaryKeyConstraint('merchant_journey_event_id')
    )
    op.create_table('shopper_profiles',
    sa.Column('shopper_id', sa.UUID(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Numeric(), nullable=False),
    sa.Column('average_order_value', sa.Numeric(), nullable=False),
    sa.Column('customer_lifetime_value', sa.Numeric(), nullable=False),
    sa.Column('purchase_frequency', sa.Numeric(), nullable=False),
    sa.Column('wishlist_item_count', sa.Integer(), nullable=False),
    sa.Column('save_for_later_item_count', sa.Integer(), nullable=False),
    sa.Column('cart_abandonment_count', sa.Integer(), nullable=False),
    sa.Column('campaign_engagement_count', sa.Integer(), nullable=False),
    sa.Column('preferred_category', sa.String(), nullable=True),
    sa.Column('preferred_size', sa.String(), nullable=True),
    sa.Column('last_purchase_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifecycle_stage', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shopper_id'], ['shoppers.shopper_id'], ),
    sa.PrimaryKeyConstraint('shopper_id')
    )
    op.create_table('shopper_segment_members',
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('shopper_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['shopper_segments.segment_id'], ),
    sa.ForeignKeyConstraint(['shopper_id'], ['shoppers.shopper_id'], ),
    sa.PrimaryKeyConstraint('segment_id', 'shopper_id')
    )
    op.create_table('customer_journeys',
    sa.Column('journey_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('shopper_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('journey_status', sa.String(), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('entry_source', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['shopper_id'], ['shoppers.shopper_id'], ),
    sa.PrimaryKeyConstraint('journey_id')
    )
    op.create_table('customer_journey_events',
    sa.Column('journey_event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('source_event_category', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['customer_journeys.journey_id'], ),
    sa.PrimaryKeyConstraint('journey_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_journey_events')
    op.drop_table('customer_journeys')
    op.drop_table('shopper_segment_members')
    op.drop_table('shopper_profiles')
    op.drop_table('merchant_journey_events')
    op.drop_table('merchant_profiles')
    op.drop_table('merchant_journeys')
    op.drop_table('merchant_health')
    # ### end Alembic commands ###
