"""investigation tables

Revision ID: a1770327f2ef
Revises: f1c7f5c49cfa
Create Date: 2026-09-12 23:24:11.262451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1770327f2ef'
down_revision: Union[str, Sequence[str], None] = 'f1c7f5c49cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('investigation_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('investigation_id')
    )
    op.create_table('investigation_messages',
    sa.Column('message_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_investigation_messages_investigation_id'), 'investigation_messages', ['investigation_id'], unique=False)
    op.create_table('investigation_tool_executions',
    sa.Column('tool_execution_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ),
    sa.PrimaryKeyConstraint('tool_execution_id')
    )
    op.create_index(op.f('ix_investigation_tool_executions_investigation_id'), 'investigation_tool_executions', ['investigation_id'], unique=False)
    op.create_table('investigation_evidence',
    sa.Column('evidence_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('tool_execution_id', sa.UUID(), nullable=True),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ),
    sa.ForeignKeyConstraint(['tool_execution_id'], ['investigation_tool_executions.tool_execution_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_investigation_evidence_investigation_id'), 'investigation_evidence', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_evidence_investigation_id'), table_name='investigation_evidence')
    op.drop_table('investigation_evidence')
    op.drop_index(op.f('ix_investigation_tool_executions_investigation_id'), table_name='investigation_tool_executions')
    op.drop_table('investigation_tool_executions')
    op.drop_index(op.f('ix_investigation_messages_investigation_id'), table_name='investigation_messages')
    op.drop_table('investigation_messages')
    op.drop_table('investigations')
    # ### end Alembic commands ###
