"""Add processing state foundation

Revision ID: d09b8ab066a4
Revises: c619c8f70888
Create Date: 2026-10-01 16:57:04.277849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09b8ab066a4'
down_revision: Union[str, Sequence[str], None] = 'c619c8f70888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_processing_states',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_generation_status', sa.String(), server_default='PENDING', nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entity_type', 'entity_id', 'target_type')
    )
    op.add_column('campaigns', sa.Column('last_business_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_campaigns_last_business_activity_at'), 'campaigns', ['last_business_activity_at'], unique=False)
    op.add_column('merchants', sa.Column('last_business_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_merchants_last_business_activity_at'), 'merchants', ['last_business_activity_at'], unique=False)
    op.add_column('shoppers', sa.Column('last_business_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_shoppers_last_business_activity_at'), 'shoppers', ['last_business_activity_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shoppers_last_business_activity_at'), table_name='shoppers')
    op.drop_column('shoppers', 'last_business_activity_at')
    op.drop_index(op.f('ix_merchants_last_business_activity_at'), table_name='merchants')
    op.drop_column('merchants', 'last_business_activity_at')
    op.drop_index(op.f('ix_campaigns_last_business_activity_at'), table_name='campaigns')
    op.drop_column('campaigns', 'last_business_activity_at')
    op.drop_table('entity_processing_states')
    # ### end Alembic commands ###
