"""Add EntityDomainActivity and remove operational activity timestamps

Revision ID: f32720ce8c5f
Revises: d09b8ab066a4
Create Date: 2026-10-01 18:19:17.997595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f32720ce8c5f'
down_revision: Union[str, Sequence[str], None] = 'd09b8ab066a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_domain_activities',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entity_type', 'entity_id', 'domain')
    )
    op.drop_index(op.f('ix_campaigns_last_business_activity_at'), table_name='campaigns')
    op.drop_column('campaigns', 'last_business_activity_at')
    op.drop_index(op.f('ix_merchants_last_business_activity_at'), table_name='merchants')
    op.drop_column('merchants', 'last_business_activity_at')
    op.drop_index(op.f('ix_shoppers_last_business_activity_at'), table_name='shoppers')
    op.drop_column('shoppers', 'last_business_activity_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppers', sa.Column('last_business_activity_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_shoppers_last_business_activity_at'), 'shoppers', ['last_business_activity_at'], unique=False)
    op.add_column('merchants', sa.Column('last_business_activity_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_merchants_last_business_activity_at'), 'merchants', ['last_business_activity_at'], unique=False)
    op.add_column('campaigns', sa.Column('last_business_activity_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_campaigns_last_business_activity_at'), 'campaigns', ['last_business_activity_at'], unique=False)
    op.drop_table('entity_domain_activities')
    # ### end Alembic commands ###
